### ISSUE TITLE
LLM利用について追記

### ISSUE THREAD

**Issue by blendthink** [yumemi-inc/flutter-engineer-codecheck#10]
## 背景

以前からあったが、 ChatGPT 4 が発表され、これをどう活かすかがとても重要なフェーズになってきた

## 達成したいこと

Android のコーディング試験のように README の参考記事のどこかに AI サービスの利用について記載する

https://github.com/yumemi-inc/android-engineer-codecheck/pull/20

**Comment by YumNumm** [comment]
@blendthink こちら対応しても良いでしょうか?

**Comment by blendthink** [comment]
@YumNumm 
はい！大丈夫です！
コメントくださり、ありがとうございます😍 
アサインさせていただきました〜
