### ISSUE TITLE
GitHub APIは直接利用が必要？あるいは手段は問わない？

### ISSUE THREAD

**Issue by mono0926** [yumemi-inc/flutter-engineer-codecheck#5]
> GitHub のリポジトリを検索する際、GitHub API（[search/repositories](https://docs.github.com/ja/rest/reference/search#search-repositories)）を利用する
> https://github.com/yumemi-inc/flutter-engineer-codecheck/blob/main/README.md#動作

こう記載されてますが、 例えば [github | Dart Package](https://pub.dev/packages/github) のようにそれをラップしたパッケージの利用は不可ですか？(現状の書き方だと不可に見えます)

個人的には、手段問わずでも良い気がしますが、もしGitHub APIの直接利用を強制する場合(APIを叩く実装を見たい場合)、以下のように補足するとより分かりやすくなりそうです。

- GitHub のリポジトリを検索する際、GitHub API（[search/repositories](https://docs.github.com/ja/rest/reference/search#search-repositories)）を利用する
  - [github | Dart Package](https://pub.dev/packages/github) のようなパッケージは利用せずAPIを呼ぶ処理を自分で実装すること

**Comment by watanavex** [comment]
私はRestAPIを直接叩く に限定したいです 🤔 

httpのやりとり、json文字列の取り扱いは多くのアプリで発生する課題であり、
これらにどうアプローチするか？がこの課題の大事なポイントの一つだと思っています。

**Comment by mono0926** [comment]
@watanavex 

なるほど、それはそうですね 👌 

#6 で僕が挙げた、GitHub認証してプロフィール更新という要件をもし足すと、自前実装だとちょっと面倒かも(パッケージ利用で済ませても良さそう)と思いながら、これを起票した次第でした。

> 以下のように補足するとより分かりやすくなりそうです。

補足がないと、内部的にそれが利用されているパッケージ利用でも良いのかどうか不明瞭かもと少し気になりました。

**Comment by watanavex** [comment]
> 補足がないと、内部的にそれが利用されているパッケージ利用でも良いのかどうか不明瞭かもと少し気になりました。

そうですね、現状iOS/Androidでもパッケージを使った方は現れていませんが、明記しても良さそうと思いました 🤔
blendthink さん、どうおもいますか？

**Comment by blendthink** [comment]
@mono0926 @watanavex 
ラップしたパッケージの利用について考慮していませんでした。。

考えとしては渡部さんと同じです！
明記していた方が良さそうなので、今からプルリク出します！
